# Generated by Django 2.0.4 on 2018-09-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('dateofbirth', models.CharField(max_length=30)),
                ('employeeid', models.CharField(max_length=30)),
                ('joiningdate', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('possition', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=30)),
                ('reviewer', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
